
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async getMyIdentity() : Promise<IdentityInfo> {
    return await TAURI_INVOKE("get_my_identity");
},
async startDiscovery() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_discovery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually connect to a peer by IP address and port.
 * Used as fallback when mDNS is unavailable.
 */
async connectManual(ip: string, port: number) : Promise<Result<PeerRow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_manual", { ip, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPeers() : Promise<Result<PeerRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trustPeer(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trust_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async blockPeer(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("block_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async untrustPeer(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("untrust_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an outbound TCP connection to a peer and register it in the ConnectionManager.
 * 
 * Looks up the peer's IP and port from the database by fingerprint.
 * Emits `peer:connected` on success and `peer:disconnected` when the connection drops.
 * 
 * Per RULES.md §4: 5-second connection timeout, non-blocking I/O via tokio.
 */
async connectToPeer(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_to_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether there is a live TCP connection to the given peer fingerprint.
 */
async getConnectionStatus(fingerprint: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_status", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop the TCP connection to a peer by removing it from the ConnectionManager.
 * The drop of the OwnedWriteHalf will close the socket.
 */
async disconnectPeer(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send our handshake to a connected peer
 */
async sendHandshake(fingerprint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_handshake", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a text message to a peer
 */
async sendMessage(fingerprint: string, content: string, replyTo: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { fingerprint, content, replyTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get message history for a peer
 */
async getMessages(fingerprint: string) : Promise<Result<MessageRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send typing indicator to a peer
 */
async sendTyping(args: SendTypingArgs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_typing", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type IdentityInfo = { public_key: string; fingerprint: string }
export type MessageRow = { id: number; message_id: string; peer_fingerprint: string; direction: string; content: string; timestamp: number; reply_to: string | null; status: string }
export type PeerRow = { id: number; fingerprint: string; display_name: string | null; hostname: string | null; ip_address: string | null; port: number; trust_level: string; is_online: boolean; last_seen: string | null; network_interface: string | null }
export type SendTypingArgs = { fingerprint: string; is_typing: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
