
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
        /**
 * @param { string } name
 * @returns { Promise<string> }
 */
async greet(name)  {
    return await TAURI_INVOKE("greet", { name });
},
/**
 * @returns { Promise<IdentityInfo> }
 */
async getMyIdentity()  {
    return await TAURI_INVOKE("get_my_identity");
},
/**
 * @returns { Promise<Result<string, string>> }
 */
async startDiscovery()  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_discovery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Manually connect to a peer by IP address and port.
 * Used as fallback when mDNS is unavailable.
 * @param { string } ip
 * @param { number } port
 * @returns { Promise<Result<PeerRow, string>> }
 */
async connectManual(ip, port)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_manual", { ip, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @returns { Promise<Result<PeerRow[], string>> }
 */
async listPeers()  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_peers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async trustPeer(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trust_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async blockPeer(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("block_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async untrustPeer(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("untrust_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Open an outbound TCP connection to a peer and register it in the ConnectionManager.
 * 
 * Looks up the peer's IP and port from the database by fingerprint.
 * Emits `peer:connected` on success and `peer:disconnected` when the connection drops.
 * 
 * Per RULES.md §4: 5-second connection timeout, non-blocking I/O via tokio.
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async connectToPeer(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_to_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Check whether there is a live TCP connection to the given peer fingerprint.
 * @param { string } fingerprint
 * @returns { Promise<Result<boolean, string>> }
 */
async getConnectionStatus(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_status", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Drop the TCP connection to a peer by removing it from the ConnectionManager.
 * The drop of the OwnedWriteHalf will close the socket.
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async disconnectPeer(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_peer", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Send our handshake to a connected peer
 * @param { string } fingerprint
 * @returns { Promise<Result<null, string>> }
 */
async sendHandshake(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_handshake", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Send a text message to a peer
 * @param { string } fingerprint
 * @param { string } content
 * @param { string | null } replyTo
 * @returns { Promise<Result<string, string>> }
 */
async sendMessage(fingerprint, content, replyTo)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { fingerprint, content, replyTo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Get message history for a peer
 * @param { string } fingerprint
 * @returns { Promise<Result<MessageRow[], string>> }
 */
async getMessages(fingerprint)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_messages", { fingerprint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
},
/**
 * Send typing indicator to a peer
 * @param { SendTypingArgs } args
 * @returns { Promise<Result<null, string>> }
 */
async sendTyping(args)  {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_typing", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  };
}
}
    }

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * @typedef { { public_key: string; fingerprint: string } } IdentityInfo
 */

/**
 * @typedef { { id: number; message_id: string; peer_fingerprint: string; direction: string; content: string; timestamp: number; reply_to: string | null; status: string } } MessageRow
 */

/**
 * @typedef { { id: number; fingerprint: string; display_name: string | null; hostname: string | null; ip_address: string | null; port: number; trust_level: string; is_online: boolean; last_seen: string | null; network_interface: string | null } } PeerRow
 */

/**
 * @typedef { { fingerprint: string; is_typing: boolean } } SendTypingArgs
 */


/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";

/** @typedef {typeof import("@tauri-apps/api/window").WebviewWindowHandle} __WebviewWindowHandle__ */

/**
 * @template T
 * @typedef {{
 *   listen: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
 *	 once: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
 *	 emit: T extends null
 *	   ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
 *     : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
 *	}} __EventObj__<T>
 */

/**
 * @template T,E
 * @typedef { { status: "ok", data: T } | { status: "error", error: E } } Result
 */

/**
 * @template {Record<string, any>} T
 * @param {Record<keyof T, string>} mappings
 * @returns {{
 * 	 [K in keyof T]: __EventObj__<T[K]> & {
 *	   (handle: __WebviewWindowHandle__): __EventObj__<T[K]>;
 *   };
 * }}
 */
function __makeEvents__(mappings) {
	return new Proxy(
		{},
		{
			get: (_, event) => {
				const name = mappings[event];

				new Proxy(() => {}, {
					apply: (_, __, [window]) => ({
						listen: (arg) => window.listen(name, arg),
						once: (arg) => window.once(name, arg),
						emit: (arg) => window.emit(name, arg),
					}),
					get: (_, command) => {
						switch (command) {
							case "listen":
								return (arg) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
